# Generated by Django 4.0.3 on 2022-04-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service_object',
            new_name='ServiceObject',
        ),
    ]
