# Generated by Django 4.0.3 on 2022-04-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_client_website'),
        ('ticket', '0003_employeeposition_ticketpriority_ticketstatus_and_more'),
    ]

    operations = [
    ]
