# Generated by Django 4.0.3 on 2022-04-18 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_merge_20220417_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('/(https?:\\/\\/(?:www\\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|www\\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\\.[^\\s]{2,}|https?:\\/\\/(?:www\\.|(?!www))[a-zA-Z0-9]+\\.[^\\s]{2,}|www\\.[a-zA-Z0-9]+\\.[^\\s]{2,})/gi;')], verbose_name='Вебсайт'),
        ),
    ]
