# Generated by Django 4.0.3 on 2022-04-20 07:09

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ticket.problemarea')),
            ],
            options={
                'verbose_name': 'Проблемная область',
                'verbose_name_plural': 'Проблемные области',
                'db_table': 'problem_area',
            },
        ),
    ]
