# Generated by Django 4.0.3 on 2022-04-20 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0007_department_servicelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения заявки')),
                ('received_at', models.DateTimeField(default=None, null=True, verbose_name='Дата получения заявки')),
                ('desired_to', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Желаемая дата исполнения')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('closed_at', models.DateTimeField(default=None, null=True, verbose_name='Дата закрытия заявки')),
                ('work_started_at', models.DateTimeField(default=None, null=True, verbose_name='Дата начала работ')),
                ('work_finished_at', models.DateTimeField(default=None, null=True, verbose_name='Дата окончания работ')),
                ('ride_started_at', models.DateTimeField(default=None, null=True, verbose_name='Дата начала поездки')),
                ('ride_finished_at', models.DateTimeField(default=None, null=True, verbose_name='Дата окончания поездки')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина отмены заявки')),
                ('client', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.client', verbose_name='Клиент')),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.department', verbose_name='Департамент')),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Водитель')),
                ('executor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executor_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('priority', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.ticketpriority', verbose_name='Приоритет')),
                ('problem_areas', models.ManyToManyField(related_name='tickets', to='ticket.problemarea')),
                ('service_level', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.servicelevel', verbose_name='Уровень обслуживания')),
                ('service_object', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.serviceobject', verbose_name='Объект обслуживания')),
                ('status', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.ticketstatus', verbose_name='Статус заявки')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.tickettype', verbose_name='Тип заявки')),
                ('works', models.ManyToManyField(related_name='tickets', to='ticket.work')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'ticket',
            },
        ),
    ]
