# Generated by Django 4.0.3 on 2022-04-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
