# Generated by Django 4.0.3 on 2022-04-23 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0009_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='desired_to',
            field=models.DateTimeField(default=None, null=True, verbose_name='Желаемая дата исполнения'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='driver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Водитель'),
        ),
    ]
