# Generated by Django 4.0.3 on 2022-04-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_client_website'),
        ('ticket', '0009_delete_employee'),
    ]

    operations = [
    ]
