# Generated by Django 4.0.3 on 2022-04-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_ticket_desired_to_alter_ticket_driver'),
        ('ticket', '0010_merge_0006_alter_client_website_0009_delete_employee'),
    ]

    operations = [
    ]
