# Generated by Django 4.0.3 on 2022-04-27 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_merge_20220424_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default=4, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.ticketstatus', verbose_name='Статус заявки'),
        ),
    ]
