# Generated by Django 4.0.3 on 2022-04-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_ticket_cancel_reason_alter_ticket_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('see_engineer_tickets', 'Может видеть только заявки со статусами Назначенный, На исполнении, Заверщенный')], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
