# Generated by Django 4.0.3 on 2022-04-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('see_engineer_tickets', 'Может видеть только заявки со статусами Назначенный, На исполнении, Заверщенный'), ('see_operator_tickets', 'Может видеть только заявки со статусами Неопределенный, Подготовленный')], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
