# Generated by Django 4.0.3 on 2022-05-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='ticket.region', verbose_name='Область'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceobject',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='service_objects', to='ticket.region', verbose_name='Область'),
            preserve_default=False,
        ),
    ]
