# Generated by Django 4.0.3 on 2022-05-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_alter_serviceobject_criterion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус договора',
                'verbose_name_plural': 'Статусы договоров',
                'db_table': 'contract_status',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Типы договоров',
                'db_table': 'contract_type',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=50, verbose_name='№ Документа')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_until', models.DateField(verbose_name='Действует до')),
                ('current_document', models.FileField(upload_to='contracts', verbose_name='Действующий документ')),
                ('time_to_fix_SLA', models.TimeField(blank=True, default=None, null=True, verbose_name='Время на устранение проблемы')),
                ('company_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='ticket.client', verbose_name='Компания-клиент')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='ticket.department', verbose_name='Департамент')),
                ('service_objects_SLA', models.ManyToManyField(blank=True, default=None, related_name='contracts', to='ticket.serviceobject')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='ticket.contractstatus', verbose_name='Статус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='ticket.contracttype', verbose_name='Тип договора')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
                'db_table': 'contract',
            },
        ),
    ]
