# Generated by Django 4.0.3 on 2022-05-05 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_contract_time_to_fix_problem_sla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='time_to_fix_SLA',
        ),
    ]
