# Generated by Django 4.0.3 on 2022-05-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_remove_contract_time_to_fix_sla'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('name',)},
        ),
    ]
