# Generated by Django 4.0.3 on 2022-05-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0027_delete_employeeposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='ticket.country', verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
