# Generated by Django 4.0.3 on 2022-05-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0028_region_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('see_engineer_tickets', 'Может видеть только заявки со статусами Назначенный, На исполнении, Заверщенный'), ('see_operator_tickets', 'Может видеть только заявки со статусами Неопределенный, Подготовленный'), ('see_chief_tickets', 'Может видеть только заявки со статусами Подготовленный, Назначенный, Завершенный, Отмененный, На исполнении, Исполненный'), ('close_ticket', 'Может закрывать заявки')], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
