# Generated by Django 4.0.3 on 2022-05-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0030_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='close_commentary',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий к закрытию заявки'),
        ),
    ]
