# Generated by Django 4.0.3 on 2022-05-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0031_ticket_close_commentary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='service_objects_SLA',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='time_to_fix_problem_SLA',
        ),
        migrations.AddField(
            model_name='serviceobject',
            name='guarantee_valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Гаранития действует с'),
        ),
        migrations.AddField(
            model_name='serviceobject',
            name='guarantee_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия действует до'),
        ),
        migrations.AddField(
            model_name='serviceobject',
            name='time_to_fix_problem',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Время на устранение проблемы'),
        ),
    ]
