# Generated by Django 4.0.3 on 2022-05-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0032_remove_contract_service_objects_sla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='work_done',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Проделанная работа'),
        ),
    ]
