# Generated by Django 4.0.3 on 2022-05-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_ticket_work_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='desired_to',
            field=models.DateTimeField(default=None, null=True, verbose_name='Желаемая дата и время исполнения'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='received_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время получения заявки'),
        ),
    ]
