# Generated by Django 4.0.3 on 2022-05-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_ticket_work_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='current_document',
        ),
        migrations.AlterField(
            model_name='serviceobject',
            name='criterion',
            field=models.ForeignKey(default='Гарантийный', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_objects', to='ticket.criteriontype', verbose_name='Критерий'),
        ),
        migrations.AlterField(
            model_name='serviceobject',
            name='guarantee_valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='Гарантия действует с'),
        ),
        migrations.CreateModel(
            name='ContractFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_document', models.FileField(upload_to='contracts', verbose_name='Действующий документ')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_files', to='ticket.contract')),
            ],
            options={
                'verbose_name': 'Действующий документ',
                'verbose_name_plural': 'Действующие документы',
                'db_table': 'contract_files',
            },
        ),
    ]
