# Generated by Django 4.0.3 on 2022-05-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0037_sparepartuser_assigned_by_sparepartuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartuser',
            name='service_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.serviceobject', verbose_name='Сервисный объект'),
        ),
        migrations.AddField(
            model_name='sparepartuser',
            name='status',
            field=models.CharField(choices=[('assigned', 'Назначенный'), ('set', 'Установленный'), ('returned', 'Возвращенный')], default='Назначенный', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='sparepartuser',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket.ticket', verbose_name='Заявка'),
        ),
    ]
