# Generated by Django 4.0.3 on 2022-05-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0038_sparepartuser_service_object_sparepartuser_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartuser',
            name='status',
            field=models.CharField(choices=[('assigned', 'Назначенный'), ('set', 'Установленный'), ('returned', 'Возвращенный')], default='assigned', max_length=20, verbose_name='Статус'),
        ),
    ]
