# Generated by Django 4.0.3 on 2022-05-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0040_ticket_expected_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartuser',
            name='status',
            field=models.CharField(choices=[('Назначенный', 'Назначенный'), ('set', 'Установленный'), ('returned', 'Возвращенный')], default='Назначенный', max_length=20, verbose_name='Статус'),
        ),
    ]
