# Generated by Django 4.0.3 on 2022-05-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0042_alter_sparepartuser_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepartuser',
            options={'permissions': [('see_engineer_spare_parts', 'Может видеть только запчасти со статусами Назначенный, Установленный')], 'verbose_name': 'Передача запчасти инженеру', 'verbose_name_plural': 'Передача запчастей инженеру'},
        ),
    ]
