# Generated by Django 4.0.3 on 2022-06-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0043_alter_sparepartuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='faralost@gmail.com', max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
