# Generated by Django 4.0.3 on 2022-06-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0044_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Серийный №'),
        ),
    ]
