# Generated by Django 4.0.3 on 2022-06-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0046_alter_sparepart_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Серийный №'),
        ),
    ]
